### PR TITLE
Added build && release automation using github actions

### PR DESCRIPTION
**Pull request by shikharvashistha**
@shinebayar-g 
Fixed : #20 && #21

Reference [here](https://github.com/shikharvashistha/ufw-docker-automated/pull/2)

### CODE REVIEW

**Comment by shinebayar-g** [comment]
Hi. Thanks for the PR. Continuous build LGTM. Release workflow needs more updates. It has to do the following:

- Do everything in the build
- Create new GH release
- Upload build to the body of the GH release
- Body has to be dynamic or just empty for now.

If you want to make updates to the release or just want to merge build only changes in this PR, either will work.

**Comment by shikharvashistha** [comment]
> Hi. Thanks for the PR. Continuous build LGTM. Release workflow needs more updates. It has to do the following:
> 
> * Do everything in the build
> * Create new GH release
> * Upload build binary to the assets of the GH release
> * Body text has to be dynamically generated or just empty for now.
> 
> If you want to make updates to the release or just want to merge build only changes in this PR, please do the accordingly. Either will work. :)

Okay, I would like to work on release workflow later and want to merge the CI build for now. Should I rebase or create a new PR what would suit you better ?

**Comment by shinebayar-g** [comment]
You can just update this PR, rebase & force push with only build changes should work.

**Comment by shikharvashistha** [comment]
> You can just update this PR, rebase & force push with only build changes should work.

Done !

**Pull request merged**
