### PR TITLE
Feature filter outgoing traffic with UFW_TO and UFW_DENY_OUTGOING labels

### PR DESCRIPTION
**Pull request by mlollo**
Since this feature is already implemented and seems to work during my tests. I think it's better to implement the #5 feature before #4. I renamed labels as discussed in the last [PR](https://github.com/shinebayar-g/ufw-docker-automated/pull/3).

Example : 
```
version: '2.4'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    labels:
      - UFW_MANAGED=true
      - UFW_ALLOW_FROM=192.168.0.0/24
      - UFW_DENY_OUTGOING=true
      - UFW_ALLOW_TO=any:53;deb.debian.org:80/tcp;security.debian.org:80/tcp;192.168.2.0/24;192.168.3.0/24:tcp
    ports:
      - 80:80
```

I also add some modifications : remove sudo in ufw commands, modify prints*, add some validation methods**. Let me know if those suggestions work for you.

*I added `ufw-docker-automated: ` prefix to easily find logs in syslog file using the command `sudo cat /var/log/syslog | grep ufw-docker-automated`
**For hostname validation the source is [https://stackoverflow.com/questions/2532053/validate-a-hostname-string](https://stackoverflow.com/questions/2532053/validate-a-hostname-string). hostname validation is a mess so we'll be a bit more permissive (example with underscores), and if the hostname is not resolved no ufw rules will be added. In this case, RFC feels like the bible there's different interpretations.

### CODE REVIEW

**Comment by shinebayar-g** [comment]
Hi @mlollo 
Can you separate PR into multiple small ones?

For example, we would like to introduce renaming of `UFW_FROM` => `UFW_ALLOW_FROM` in a separate single PR. This PR's goal is out of scope. Also hostname lookup change should be introduced in separate PR etc.

I would say even port validation function is feature on its own, right?

**Comment by mlollo** [comment]
Hi @shinebayar-g, 
Sorry I'm not used to work with PR, you right one feature per PR is better.

I'll try my best to do separate PRs. I think I'll do rewrite git history since I already did it last time. Maybe I can leave in the main branch only "ufw allow to IP" feature. And from my main branch I create feature branches where I can submit separate PRs (like label renaming and hostname lookup in UFW_ALLOW_TO label).

Can I argue that port validation is a part of this PR because we don't want to allow the user to input unwanted value. For example without port validation I managed to put a port higher than 65535 in iptables using ufw command. I'm not sure this is intended. Or in this PR "ufw allow to IP" we should allow only ipnet and after we can add the possibility to accept ipnet:port in a second PR with port validation ?

**Comment by shinebayar-g** [comment]
Yeah, you don't have to rewrite your git. Just create separate branch for it.
Sure , yeah sounds good. But yeah, validation still sounds big enough for its own PR 😃

**Comment by mlollo** [comment]
Hello,

I separated in 3 branches port and host validation and label renaming.
Here, in the main branch, I kept the ufw-to feature where improved and simplified some conditionals hierarchy when parsing labels or when creating ufw-from rules.
Let me know if line 115 is good for you, because the last print is not relevant any more because of ufw-to rules. So I thought printing the deleted ufw rule is better to understand what rule is actually deleted.

Here the merge order for the PRs : 
1. Feature UFW_TO port validation
2. Feature UFW_TO host validation
3. Enhancement label renaming UFW_* => UFW_ALLOW_*

**Pull request merged**
